name: keylink
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy=1.21
  - scipy=1.7
  - matplotlib=3.4
  - jupyter=1.0 # For easier debugging by running parts of files interactively in vscode